- src/components/common/searchBar/index.tsx
- src/components/common/searchBar/styles.ts
- Search Bar 공통 컴포넌트 생성
close #32
> 💄 Feat: Search Bar 공통 컴포넌트 생성

- src/components/common/chip/index.tsx
- src/components/common/chip/styles.ts
- src/components/common/dropdown/index.tsx
- src/components/common/dropdown/styles.ts
- src/components/common/iconLabel/index.tsx
- src/components/common/searchBar/index.tsx
> 🚨 Fix: build error 수정

- src/components/common/chip/index.tsx
> 💄 공통 컴포넌트 chip 수정

- src/assets/icons/ClearIcon.tsx
- ClearIcon width, height prop 추가
close #46
> 💄 Fix: ClearIcon 크기 설정 가능하게 수정

- src/components/common/chip/index.tsx
- src/components/common/dropdown/index.tsx
- src/components/common/dropdown/styles.ts
- src/components/common/generalHeader/index.tsx
- src/components/common/textLabel/styles.ts
-  text label - flex 안에 있을 때 커지는 문제
-  general header - sub onClick 추가
-  dropdown - 열렸을 때 text 및 아래 content 보이도록 수정
-  chip - onClick 함수명 변경
close #55
> Yoon/#55 공통 컴포넌트 수정

- src/components/myTrip/plan/styles.ts
- src/components/myTrip/planGenerating/index.tsx
- src/components/myTrip/planGenerating/styles.ts
내여행 bottom section height 수정
close #63
> 💄 Fix: 내여행 bottom section height

- src/components/home/CurrentLoaction/index.tsx
- src/pages/home/HomePage.tsx
- src/pages/home/location/LocationPage.tsx
- src/pages/home/location/styles.ts
> ✨ Feat: 홈 > 위치 바꾸기

- package-lock.json
- package.json
- src/apis/instance.ts
- src/apis/travel/travel.apis.ts
- src/apis/travel/travel.queries.ts
- src/apis/travel/travel.type.ts
- src/components/community/PostList/index.tsx
- src/components/community/PostList/styles.ts
- src/main.tsx
- src/pages/myTripList/MyTripListPage.tsx
- tsconfig.app.json
[feat&style]: 내 여행 목록 가져오기 api 연동 및 퍼블리싱 수정 작업
- axios instance 기틀 마련
- tanstack query 기틀 마련
- 내 여행 목록 get api 테스트 연동 (userId관련해 백엔드 코드 및 명세서 수정 필요한 상황)
퍼블리싱
- 커뮤니티 페이지 - 반응형을 고려해 수정
close #58
> Sol/#58 [feat&style]: 내 여행 목록 가져오기 api 연동 및 퍼블리싱 수정 작업

- src/constants/homePageConstants.ts
- src/constants/path.ts
- src/pages/home/HomePage.tsx
- src/pages/home/detail/DetailPage.tsx
- src/pages/home/like/LikePage.tsx
- src/pages/home/location/LocationPage.tsx
- src/pages/home/notification/NotificationPage.tsx
- src/pages/home/popularPlace/PopularPlacePage.tsx
- src/pages/home/recommendPlace/RecommendPlacePage.tsx
- src/pages/home/search/SearchPage.tsx
- src/pages/home/search/SearchResultPage.tsx
- src/routes/AppRouter.tsx
라우팅 이동으로 페이지 분리
-  위치 바꾸기
-  검색
-  좋아요 모음
-  알림센터
-  추천 장소 더보기
-  인기 관광지 둘러보기
-  장소 상세 페이지
close #69
> ♻️ Refactor: 컴포넌트 > 라우터로 분리

- src/apis/myTrip/myTrip.apis.ts
- src/apis/myTrip/myTrip.queries.ts
- src/atoms/myTrip/planAtom.ts
- src/components/myTrip/planGenerating/index.tsx
- src/components/myTrip/toast/styles.ts
- src/constants/myTripPageConstants.ts
- src/pages/myTrip/MyTripPage.tsx
- src/pages/myTrip/addPlace/AddPlacePage.tsx
- src/pages/myTrip/editPlan/EditPlanPage.tsx
- src/pages/myTrip/plan/PlanPage.tsx
- src/pages/myTrip/tripIsland/recommendationIsland/RecommendedIsland.tsx
- src/pages/myTrip/tripIsland/search/TripIslandSearchPage.tsx
> Yoon/#62 내여행 api 연동 관련 코드 수정

- custom.d.ts
- src/apis/businessReview/businessReview.apis.ts
- src/apis/businessReview/businessReview.queries.ts
- src/apis/instance.ts
- src/apis/myTrip/myTrip.apis.ts
- src/apis/place/place.apis.ts
- src/apis/travel/travel.apis.ts
- src/pages/myTripRecord/MyTripRecordPage.tsx
이미지 네이티브 통신 기능 및 customAxiosMultipart 추가
formdata 통신을 위한 customAxiosMultipart 추가
close #72
> feat: 이미지 네이티브 통신 기능 및 customAxiosMultipart 추가

- src/App.tsx
- src/apis/myTrip/myTrip.queries.ts
- src/pages/myTrip/addPlace/AddPlacePage.tsx
- src/pages/myTrip/plan/PlanPage.tsx
- src/pages/myTrip/tripIsland/recommendationIsland/RecommendedIslandPage.tsx
- src/pages/myTrip/tripIsland/search/TripIslandSearchPage.tsx
- src/pages/myTrip/tripTheme/TripThemePage.tsx
- src/pages/popularPlace/PopularPlacePage.tsx
- src/pages/recommendPlace/RecommendPlacePage.tsx
QueryClient 추가 및 로딩, 에러 처리
close #
> Yoon/#62 QueryClient 추가 및 로딩, 에러 처리

- src/App.tsx
> 🔥 Chore: QueryClient 중복 제거

- src/apis/businessReview/businessReview.queries.ts
- src/apis/travel/travel.type.ts
- src/atoms/myTrip/planAtom.ts
- src/components/common/textArea/index.tsx
- src/components/common/textField/TextField.tsx
- src/components/myTripRecord/DetailTravelMemories/index.tsx
- src/pages/myTripList/MyTripListPage.tsx
- src/pages/myTripRecord/MyTripRecordPage.tsx
- src/pages/myTripRecordDetail/MyTripRecordDetailPage.tsx
> feat: 추억 기록 id 연결 및 일부 작업 주석 처리

- src/pages/home/search/SearchResultPage.tsx
> ✨ Feat: 검색 결과 찜하기 여부 추가

- src/apis/businessReview/businessReview.type.ts
- src/apis/travel/travel.type.ts
- src/components/myTripList/TripCard/index.tsx
- src/pages/myTripList/MyTripListPage.tsx
- src/pages/myTripRecordDetail/MyTripRecordDetailPage.tsx
> feat: api 데이터 변동 사항에 맞게 수정

- src/components/myTrip/plan/index.tsx
- src/pages/myTrip/plan/PlanPage.tsx
> chore: 날짜 형식 수정

- src/components/home/MyTrip/index.tsx
- src/components/home/MyTrip/styles.ts
- src/components/home/MyTripToday/index.tsx
홈 페이지 > 내여행 추억, 내여행 당일
close #
> Yoon/#62 홈 페이지 > 내여행 추억, 내여행 당일  @seoyoonOh

- src/components/home/MyTrip/index.tsx
- src/components/home/MyTripToday/index.tsx
> ⚡️ add: 홈 페이지 내여행 추억 에러 바운더리

- src/components/myTrip/listComponent/index.tsx
- src/pages/myTrip/addPlace/AddPlacePage.tsx
api 이미지 url 컬럼명에 따른 코드 수정
close #
> Yoon/#62 api 이미지 url 컬럼명에 따른 코드 수정

- src/components/place/PopularPlace/index.tsx
홈 > 인기 관광지 불러온 이미지 보이도록 수정
close #
> 🐛 fix: 홈 > 인기 관광지 이미지

- src/components/myTrip/map/index.tsx
- src/pages/myTrip/editPlan/EditPlanPage.tsx
- src/pages/myTrip/generatePlan/GeneratePlanPage.tsx
- 장소 편집 페이지 이미지 처리
- 지도 장소 marker 모두 보이게 수정
close #
> Yoon/#62 내여행 수정

- src/pages/myTrip/tripSchedule/style.css
> style: 캘린더 width 화면에 맞춤

- src/components/myTrip/map/miniMap/index.tsx
- src/components/place/placeDetail/index.tsx
- src/pages/placeDetail/PlaceDetailPage.tsx
> Yoon/#62 장소 상세 페이지 수정

- src/components/home/MyTrip/index.tsx
- src/components/myTrip/planGenerating/index.tsx
- src/pages/myTrip/plan/PlanPage.tsx
> Yoon/#62 수정

- src/pages/myTrip/plan/PlanPage.tsx
> fix: 수정 완료 3초 후 페이지 리로드

- src/components/myTrip/plan/index.tsx
- src/pages/myTrip/plan/PlanPage.tsx
> Yoon/#62 일정 수정하기

- src/atoms/myTrip/planAtom.ts
- src/components/myTrip/planGenerating/index.tsx
- src/pages/myTrip/MyTripPage.tsx
- src/pages/myTrip/generatePlan/GeneratePlanPage.tsx
- src/pages/myTrip/tripIsland/TripIslandPage.tsx
- src/pages/myTrip/tripIsland/recommendationIsland/RecommendedIslandPage.tsx
- src/pages/myTrip/tripIsland/recommendationIsland/styles.ts
- src/pages/myTrip/tripIsland/search/TripIslandSearchPage.tsx
- src/pages/myTrip/tripTheme/TripThemePage.tsx
> Yoon/#62 섬 추천 > 장소 선택 리팩토링

- src/components/common/searchBar/index.tsx
- src/components/common/searchBar/styles.ts
- src/pages/myTrip/plan/PlanPage.tsx
> Yoon/#62 버그 수정
